// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    "kevent": "libs/kevent"
  });

  require(["core/menu", "core/game/main"], function(Menu, Game) {
    var gameMenu, pages, runGame;
    runGame = function() {
      var game;
      game = new Game("#game");
      return game.run(function(score) {
        gameMenu.switchPage("#end");
        return document.querySelector("#score").innerHTML = score;
      });
    };
    pages = {
      "#menu": null,
      "#game": runGame,
      "#credits": null,
      "#help": null,
      "#end": null
    };
    return gameMenu = new Menu("#main", "#menu", pages);
  });

}).call(this);
