// Generated by CoffeeScript 1.3.3
(function() {

  require.config({
    "kevent": "libs/kevent"
  });

  require(["core/game"], function(Game) {
    var game;
    game = new Game("#game");
    return game.run(function(score) {
      return console.log("score: " + score);
    });
  });

}).call(this);
