// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var Menu;
    return Menu = (function() {

      function Menu(parent, first, pages) {
        var callback, link, links, obj, selector, _i, _len, _ref;
        this.pages = pages;
        obj = this;
        _ref = this.pages;
        for (selector in _ref) {
          callback = _ref[selector];
          this.pages[selector] = {
            callback: callback,
            elem: document.querySelector(selector)
          };
        }
        this.switchPage(first);
        links = document.querySelectorAll(parent + " button[data-target]");
        for (_i = 0, _len = links.length; _i < _len; _i++) {
          link = links[_i];
          link.onclick = function(e) {
            selector = "#" + this.dataset["target"];
            return obj.switchPage(selector);
          };
        }
      }

      Menu.prototype.switchPage = function(selector) {
        var key, page, _base, _ref;
        _ref = this.pages;
        for (key in _ref) {
          page = _ref[key];
          page.elem.style.display = key === selector ? "block" : "none";
        }
        return typeof (_base = this.pages[selector]).callback === "function" ? _base.callback() : void 0;
      };

      return Menu;

    })();
  });

}).call(this);
