// Generated by CoffeeScript 1.3.3
(function() {

  define(function() {
    var _arr;
    _arr = {
      facebook: "http://facebook.com/sharer.php?s=100&p[url]={{url}}&p[title]={{title}}&p[summary]={{summary}}",
      twitter: "http://twitter.com/share?text={{title}} - {{summary}}&url={{url}}"
    };
    return function(social, title, summary) {
      var url;
      url = _arr[social];
      url = url.replace("{{url}}", window.location.href);
      url = url.replace("{{title}}", title);
      url = url.replace("{{summary}}", summary);
      return window.open(encodeURI(url));
    };
  });

}).call(this);
